name: gestr
description: "A new Flutter project."
releaseType: dev # change ReleaseType to stable for production release 'prod' || 'dev' 

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  yaml: any
  google_fonts: ^4.0.3
  easy_localization: ^3.0.0
  cupertino_icons: ^1.0.8
  flutter_svg: ^2.1.0
  firebase_core: ^3.13.0
  firebase_auth: ^5.5.3
  flutter_bloc: ^9.1.1
  dartz: ^0.10.1
  get_it: ^8.0.3
  injectable: ^2.5.0
  provider: ^6.1.5
  google_sign_in: ^6.3.0
  cloud_firestore: ^5.6.7
  fl_chart: ^1.0.0
  shared_preferences: ^2.5.3
  equatable: ^2.0.7
  image_picker: ^1.1.2
  pdf: ^3.11.3
  printing: ^5.14.2
  share_plus: ^11.0.0
  intl: ^0.19.0
  firebase_storage: ^12.4.5
  flutter_slidable: ^4.0.0
  table_calendar: ^3.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/jsons/
    - pubspec.yaml
