// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options_dev.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: String.fromEnvironment('GOOGLE_API_KEY_DEV_WEB'),
    appId: '1:663748995058:web:a8a2179d4ddceffe89ad6b',
    messagingSenderId: '663748995058',
    projectId: 'gestr-dev',
    authDomain: 'gestr-dev.firebaseapp.com',
    storageBucket: 'gestr-dev.firebasestorage.app',
    measurementId: 'G-4GLRJ7H53V',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: String.fromEnvironment('GOOGLE_API_KEY_DEV_ANDROID'),
    appId: '1:663748995058:android:d3834c037dffc08e89ad6b',
    messagingSenderId: '663748995058',
    projectId: 'gestr-dev',
    storageBucket: 'gestr-dev.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: String.fromEnvironment('GOOGLE_API_KEY_DEV_IOS'),
    appId: '1:663748995058:ios:8485adf9f09c0c2089ad6b',
    messagingSenderId: '663748995058',
    projectId: 'gestr-dev',
    storageBucket: 'gestr-dev.firebasestorage.app',
    iosBundleId: 'com.example.gestr',
  );
}
