// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB6lCtRzkY-R_0iYN7iBS859xEQwv9BIcQ',
    appId: '1:634533635704:web:b90830bdada0d81d35ef8d',
    messagingSenderId: '634533635704',
    projectId: 'gestr-58677',
    authDomain: 'gestr-58677.firebaseapp.com',
    storageBucket: 'gestr-58677.firebasestorage.app',
    measurementId: 'G-90L15PN6CD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAgkCYkT7yVJ0bELwc_SB_nVNumFt6iI9Q',
    appId: '1:634533635704:android:8a97026dfd9e3e1d35ef8d',
    messagingSenderId: '634533635704',
    projectId: 'gestr-58677',
    storageBucket: 'gestr-58677.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCTxg2PrKuybYWXyFwpHfpMdWJF6IYWPEU',
    appId: '1:634533635704:ios:fdbed3ed5aea2a8435ef8d',
    messagingSenderId: '634533635704',
    projectId: 'gestr-58677',
    storageBucket: 'gestr-58677.firebasestorage.app',
    iosBundleId: 'com.example.gestr',
  );
}
