name: PDF/A Validation

on:
  push:
    branches: [ main, master ]
  pull_request:

permissions:
  contents: read
  packages: read

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Pub get
        run: flutter pub get

      - name: Generate sample PDFs
        run: dart run tool/generate_sample_pdfs.dart

      - name: List PDFs
        run: |
          ls -la samples/pdfs || true
          
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}    

      - name: Validate with veraPDF (Docker)
        env:
          DEFAULT_VERAPDF_IMAGE: ghcr.io/verapdf/verapdf-apps:latest  
        run: |
          VERAPDF_IMAGE="${VERAPDF_IMAGE:-$DEFAULT_VERAPDF_IMAGE}"
          docker run --rm -v "${{ github.workspace }}/samples/pdfs:/work" "$VERAPDF_IMAGE" \
            --format text --maxfail 1 --failonerror /work/*.pdf

